#!/bin/bash

cat <<EOBAT
# Just some random string to allow for the "grep -A 9999999 $argv0" magic above:
# pW963GuJnrxAdWbBD2B
EOBAT

tar -C "$1" -c --owner=0 --group=0 -v -f - . | gzip -9 -c | base64 

